- name: Add OBS ppa
  become: yes
  apt_repository:
    repo: ppa:obsproject/obs-studio
    update_cache: yes

# https://support.system76.com/articles/codecs/
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ubuntu-restricted-addons

- name: Install Desktop packages
  become: true
  apt:
    name:
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - fonts-font-awesome
      - gthumb
      - mpv
      - paprefs
      - pavucontrol
      - aptitude
      - python3-pip
      - google-chrome-stable
      - obs-studio
      - flatpak
      - hunspell-el
      # - qt5-style-kvantum
      # - qt5-style-kvantum-themes

- name: Install youtube_dl
  become: true
  pip:
    name: youtube_dl
    state: latest

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add the flathub flatpak repository remote to the system installation
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  become: true
  vars:
    packages:
      - org.gtk.Gtk3theme.Pop-dark
      - com.spotify.Client
      - com.transmissionbt.Transmission
      - io.github.Qalculate
      - nl.hjdskes.gcolor3
      - com.discordapp.Discord
      - com.microsoft.Teams
      - com.mattermost.Desktop
      - com.slack.Slack
      - us.zoom.Zoom
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gimp.GIMP
      - org.audacityteam.Audacity
      - com.github.xournalpp.xournalpp
      - ws.openarena.OpenArena
      - org.openttd.OpenTTD
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
