---
# On actual servers with a management port,
# add the proper interface.

- name: Enable wake on lan service
  become: true
  systemd:
    name: wol@{{ ansible_default_ipv4.interface }}.service
    enabled: true
    state: started
    daemon_reload: true
