---
- name: Add wake-on-lan systemd service
  become: true
  copy:
    content: |
      [Unit]
      Description=Wake-on-LAN for %i
      Requires=network.target
      After=network.target

      [Service]
      ExecStart=/sbin/ethtool -s %i wol g
      Type=oneshot

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/wol@.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Enable wake on lan service
