# - name: Deploy yiannis SSH Key
#   authorized_key:
#     user: yiannis
#     key: "{{ lookup('file', lookup('env','HOME') +
#           '/.ssh/yiannis_{{ ansible_hostname }}.pub') }}"
#     state: present
#     exclusive: True

- name: Disable Password Authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Disable PAM Authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^UsePAM
    line: UsePAM no
    state: present
    backup: yes

- name: Enable Pubkey Authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PubkeyAuthentication
    line: PubkeyAuthentication yes
    state: present
    backup: yes

- name: Disable ChallengeResponse Authentication
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^ChallengeResponseAuthentication
    line: ChallengeResponseAuthentication no
    state: present
    backup: yes

- name: Disable Root Login
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
    backup: yes
  notify:
    - Restart ssh server