- name: Upgrade the OS (apt-get dist-upgrade)
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Install QEMU guest additions
  become: true
  apt: 
    name: qemu-guest-agent
  when:  ansible_facts['system_vendor'] ==  "QEMU"

- name: Install TUI/CLI packages
  become: true
  apt:
    name:
    - zsh
    - zsh-syntax-highlighting
    - command-not-found
    - atool
    - borgbackup
    - btrfs-progs
    - calcurse
    - dialog
    - docx2txt
    - fail2ban
    - fzf
    - hddtemp
    - highlight
    - htop
    - inxi
    - molly-guard
    - neofetch
    - needrestart
    - nvme-cli
    - odt2txt
    - p7zip-full
    - procinfo
    - python3-llfuse
    - sshfs
    - tmux
    - tree
    - unrar
    - w3m
    - whois
    - powertop
    - pv
    - etherwake
    - smartmontools

- name: Download exa
  become: true
  unarchive:
    src: https://github.com//ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    dest: /tmp
    remote_src: yes
  notify:
    - Move exa in to PATH


- name: Add sqlitebrowser ppa
  become: yes
  apt_repository:
    repo: ppa:linuxgndu/sqlitebrowser
    update_cache: yes

- name: Add OBS ppa
  become: yes
  apt_repository:
    repo: ppa:obsproject/obs-studio
    update_cache: yes

# https://support.system76.com/articles/codecs/
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ubuntu-restricted-addons

- name: Install Desktop packages
  become: true
  apt:
    name:
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - fonts-font-awesome
      - gthumb
      - mpv
      - paprefs
      - pavucontrol
      - aptitude
      - python3-pip
      - google-chrome-stable
      - obs-studio
      - flatpak
      - hunspell-el
      # - qt5-style-kvantum
      # - qt5-style-kvantum-themes
      - cmake
      - gitg
      - neovim
      - python3-autopep8
      - python3-pip
      - shellcheck
      - node-typescript
      - sqlitebrowser
      - nmap

- name: Install alacritty and code - Pop packages
  block:
  - name: Install alacritty and code
    become: true
    apt:
      name: ['alacritty', 'code']
  rescue:
  - debug:
      msg: 'Can not install alacritty and code. Add PPAs if you are using Ubuntu.'

# - name: Create a symbolic link for VS Code Dictionaries
#   file:
#     src: /usr/share/hunspell/*
#     dest: "{{ ansible_user_dir|quote }}/.config/Code/Dictionaries"
#     state: link
#     # ln -s /usr/share/hunspell/* ~/.config/Code/Dictionaries

- name: Install virtualization packages
  become: true
  apt:
    name: [ 'qemu', 'ebtables', 'virt-manager', 'virtualbox']
  when:  ansible_facts['system_vendor'] !=  "QEMU"

- name: Install ansible
  become: true
  pip:
    name: ['ansible','ansible-lint']
    state: latest

- name: Install Uni packages
  become: true
  apt:
    name: gretl

- name: Install youtube_dl
  become: true
  pip:
    name: youtube_dl
    state: latest

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add the flathub flatpak repository remote to the system installation
  become: yes
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  become: true
  vars:
    packages:
      - org.gtk.Gtk3theme.Pop-dark
      - com.spotify.Client
      - com.transmissionbt.Transmission
      - io.github.Qalculate
      - nl.hjdskes.gcolor3
      - com.discordapp.Discord
      - com.microsoft.Teams
      - com.mattermost.Desktop
      - com.slack.Slack
      - us.zoom.Zoom
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gimp.GIMP
      - org.audacityteam.Audacity
      - com.github.xournalpp.xournalpp
      - ws.openarena.OpenArena
      - org.openttd.OpenTTD
      - io.dbeaver.DBeaverCommunity
      - io.dbeaver.DBeaverCommunity.Client.mariadb
      - org.remmina.Remmina
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
