- name: Update cache
  become: true
  apt:
    update_cache: yes

- name: Install prerequisites for Docker repository
  become: true
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add docker apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  
- name: Install docker and it's dependencies
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add the user to the docker groups
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: start and enable docker daemon
  become: true
  service:
    name: docker
    state: started
    enabled: yes