---
- name: Disable (icmp) ping requests
  become: true
  lineinfile:
    path: /etc/ufw/before.rules
    line: "{{ item }}"
    state: absent
  with_items:
    - '-A ufw-before-input -p icmp --icmp-type source-quench -j ACCEPT'
    - '-A ufw-before-input -p icmp --icmp-type destination-unreachable -j ACCEPT'
    - '-A ufw-before-input -p icmp --icmp-type time-exceeded -j ACCEPT'
    - '-A ufw-before-input -p icmp --icmp-type parameter-problem -j ACCEPT'
    - '-A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT'